### ISSUE TITLE
'u.getUniqueID' is undefined after upgrading to v0.22.3

### ISSUE THREAD

**Issue by dluksza** [rebeccahughes/react-native-device-info#468]
## Summary

|             |     |
| ----------- | --- |
| Version     |  v0.22.3   |
| Affected OS |  ios   |
| OS Version  |  11.4   |

## Current behavior

After simple upgrade from v0.22.2 to v0.22.3 I'm getting `u.getUniqueID is undefined` nothing else has hanged in my codebase. Simple revert back to v0.22.2 fixes this issue.

Here is full log:
```
2018-08-08 11:35:26.456 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: u.getUniqueID is not a function. (In 'u.getUniqueID()', 'u.getUniqueID' is undefined)
2018-08-08 11:35:26.456828+0200 HabitChallenge[86310:8399601] Unhandled JS Exception: u.getUniqueID is not a function. (In 'u.getUniqueID()', 'u.getUniqueID' is undefined)
2018-08-08 11:35:26.475465+0200 HabitChallenge[86310:8399601] Encountered an uncaught exception. All Mixpanel instances were archived.
2018-08-08 11:35:26.476239+0200 HabitChallenge[86310:8399601] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: u.getUniqueID is not a function. (In 'u.getUniqueID()', 'u.getUniqueID' is undefined)', reason: 'Unhandled JS Exception: u.getUniqueID is not a function. (In 'u.getUniqueID..., stack:
<unknown>@729:3177
l@2:1476
<unknown>@727:1303
l@2:1476
<unknown>@726:156
l@2:1476
<unknown>@554:422
l@2:1476
<unknown>@541:236
l@2:1476
<unknown>@515:282
l@2:1476
<unknown>@514:143
l@2:1476
<unknown>@13:282
l@2:1476
<unknown>@12:39
l@2:1476
a@2:863
global code@1032:8
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001148681e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000113797031 objc_exception_throw + 48
	2   HabitChallenge                      0x000000010dcb67ad RCTFormatError + 0
	3   HabitChallenge                      0x000000010dcb33e2 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 507
	4   CoreFoundation                      0x00000001147ebccc __invoking___ + 140
	5   CoreFoundation                      0x00000001147ebb84 -[NSInvocation invoke] + 308
	6   CoreFoundation                      0x00000001148048d6 -[NSInvocation invokeWithTarget:] + 54
	7   HabitChallenge                      0x000000010dcc9db5 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 600
	8   HabitChallenge                      0x000000010dd0ffe2 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 266
	9   HabitChallenge                      0x000000010dd0fd5b ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	10  libdispatch.dylib                   0x00000001159bc7ab _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00000001159bd7ec _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001159c5be5 _dispatch_queue_serial_drain + 1305
	13  libdispatch.dylib                   0x00000001159c64fa _dispatch_queue_invoke + 328
	14  libdispatch.dylib                   0x00000001159c2344 _dispatch_queue_override_invoke + 726
	15  libdispatch.dylib                   0x00000001159c936c _dispatch_root_queue_drain + 664
	16  libdispatch.dylib                   0x00000001159c9076 _dispatch_worker_thread3 + 132
	17  libsystem_pthread.dylib             0x0000000115e78169 _pthread_wqthread + 1387
	18  libsystem_pthread.dylib             0x0000000115e77be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

## Expected behavior

Upgrading minor versions should not break client application.

**Comment by eshikerya** [comment]
same issue. sounds like changing from ```module.exports = {...}```  to ```export default {...}``` broke everything

```
(0, _reactNativeDeviceInfo.isTablet) is not a function
```

**Comment by anicolaides** [comment]
Same issue here; downgrading to 0.22.2 works fine.

**Comment by dluksza** [comment]
it seams that upgrading node to `v10.8.0` fixes this issue.

**Comment by eshikerya** [comment]
```js
import DeviceInfo from 'react-native-device-info';
```
fixes the issue

**Comment by dluksza** [comment]
Can confirm that changing import did helped, as  @eshikerya pointed out. Thanks!

**Comment by machour** [comment]
Would you mind sending a PR for the README?

**Comment by pontusab** [comment]
You can also do:


```
import DeviceInfo from 'react-native-device-info';

const { getUniqueID } = DeviceInfo
```

But I think you should be able to destruct the import directly as before.

**Comment by riskaverse** [comment]
DeviceInfo is an object which includes "default" object so, in order to access the function getUniqueID() you need to do something like this DeviceInfo.default.getUniqueID()
